// Copyright (c) 2025-2026 Himank Barve. Licensed under the VyomaOS Community License.
// See LICENSE (community) and LICENSE-COMMERCIAL (commercial) at the repository root.

pub struct Snippet {
    pub title: &'static str,
    pub lang:  &'static str,
    pub tags:  &'static str,
    pub code:  &'static [&'static str],
}

pub const SNIPPETS: &[Snippet] = &[
    Snippet {
        title: "Hello World (Rust)",
        lang:  "rust",
        tags:  "basic hello",
        code:  &[
            "fn main() {",
            "    println!(\"Hello, World!\");",
            "}",
        ],
    },
    Snippet {
        title: "Read File Lines",
        lang:  "rust",
        tags:  "file io read",
        code:  &[
            "use std::fs::File;",
            "use std::io::{BufRead, BufReader};",
            "",
            "fn read_lines(path: &str) -> Vec<String> {",
            "    let file = File::open(path).unwrap();",
            "    BufReader::new(file).lines()",
            "        .filter_map(|l| l.ok())",
            "        .collect()",
            "}",
        ],
    },
    Snippet {
        title: "HashMap Usage",
        lang:  "rust",
        tags:  "collections map",
        code:  &[
            "use std::collections::HashMap;",
            "",
            "let mut map: HashMap<String, i32> = HashMap::new();",
            "map.insert(\"count\".to_string(), 0);",
            "*map.entry(\"count\".to_string()).or_insert(0) += 1;",
            "println!(\"{:?}\", map);",
        ],
    },
    Snippet {
        title: "Struct + Impl",
        lang:  "rust",
        tags:  "struct oop",
        code:  &[
            "struct Point { x: f64, y: f64 }",
            "",
            "impl Point {",
            "    fn new(x: f64, y: f64) -> Self { Point { x, y } }",
            "    fn dist(&self, o: &Point) -> f64 {",
            "        ((self.x-o.x).powi(2) + (self.y-o.y).powi(2)).sqrt()",
            "    }",
            "}",
        ],
    },
    Snippet {
        title: "Enum + Match",
        lang:  "rust",
        tags:  "enum match pattern",
        code:  &[
            "enum Color { Red, Green, Blue }",
            "",
            "fn hex(c: Color) -> &'static str {",
            "    match c {",
            "        Color::Red   => \"#FF0000\",",
            "        Color::Green => \"#00FF00\",",
            "        Color::Blue  => \"#0000FF\",",
            "    }",
            "}",
        ],
    },
    Snippet {
        title: "Spawn Thread",
        lang:  "rust",
        tags:  "thread concurrency",
        code:  &[
            "use std::thread;",
            "",
            "let handle = thread::spawn(|| {",
            "    println!(\"running in thread\");",
            "});",
            "handle.join().unwrap();",
        ],
    },
    Snippet {
        title: "HTTP GET (TCP)",
        lang:  "rust",
        tags:  "network http tcp",
        code:  &[
            "use std::io::{Read, Write};",
            "use std::net::TcpStream;",
            "",
            "let mut stream = TcpStream::connect(\"example.com:80\")?;",
            "stream.write_all(b\"GET / HTTP/1.0\\r\\nHost: example.com\\r\\n\\r\\n\")?;",
            "let mut body = String::new();",
            "stream.read_to_string(&mut body)?;",
        ],
    },
    Snippet {
        title: "Iterate Vec",
        lang:  "rust",
        tags:  "vec iterator",
        code:  &[
            "let nums = vec![1, 2, 3, 4, 5];",
            "let doubled: Vec<i32> = nums.iter().map(|n| n * 2).collect();",
            "let evens: Vec<&i32> = nums.iter().filter(|&&n| n % 2 == 0).collect();",
            "let sum: i32 = nums.iter().sum();",
        ],
    },
    Snippet {
        title: "Error Handling",
        lang:  "rust",
        tags:  "error result",
        code:  &[
            "use std::num::ParseIntError;",
            "",
            "fn parse(s: &str) -> Result<i32, ParseIntError> {",
            "    let n: i32 = s.trim().parse()?;",
            "    Ok(n * 2)",
            "}",
            "",
            "match parse(\"42\") {",
            "    Ok(v)  => println!(\"got {v}\"),",
            "    Err(e) => eprintln!(\"error: {e}\"),",
            "}",
        ],
    },
    Snippet {
        title: "Hello World (Python)",
        lang:  "python",
        tags:  "basic hello",
        code:  &[
            "print('Hello, World!')",
        ],
    },
    Snippet {
        title: "List Comprehension",
        lang:  "python",
        tags:  "list comprehension",
        code:  &[
            "nums = [1, 2, 3, 4, 5]",
            "doubled = [n * 2 for n in nums]",
            "evens = [n for n in nums if n % 2 == 0]",
            "squares = {n: n**2 for n in nums}",
        ],
    },
    Snippet {
        title: "Read/Write File",
        lang:  "python",
        tags:  "file io",
        code:  &[
            "# read",
            "with open('file.txt') as f:",
            "    lines = f.readlines()",
            "",
            "# write",
            "with open('out.txt', 'w') as f:",
            "    f.write('hello\\n')",
        ],
    },
    Snippet {
        title: "Dataclass",
        lang:  "python",
        tags:  "class struct",
        code:  &[
            "from dataclasses import dataclass",
            "",
            "@dataclass",
            "class Point:",
            "    x: float",
            "    y: float",
            "",
            "    def dist(self, other):",
            "        return ((self.x-other.x)**2 + (self.y-other.y)**2) ** 0.5",
        ],
    },
    Snippet {
        title: "HTTP Request",
        lang:  "python",
        tags:  "network http request",
        code:  &[
            "import urllib.request",
            "import json",
            "",
            "url = 'https://api.example.com/data'",
            "with urllib.request.urlopen(url) as r:",
            "    data = json.loads(r.read())",
        ],
    },
    Snippet {
        title: "Grep Files",
        lang:  "shell",
        tags:  "search grep file",
        code:  &[
            "# Search recursively for pattern",
            "grep -rn 'pattern' ./src/",
            "",
            "# Case-insensitive, show filenames only",
            "grep -rli 'TODO' .",
        ],
    },
    Snippet {
        title: "Find and Delete",
        lang:  "shell",
        tags:  "find delete clean",
        code:  &[
            "# Find and delete .tmp files",
            "find . -name '*.tmp' -delete",
            "",
            "# Find files older than 7 days",
            "find /tmp -mtime +7 -type f",
        ],
    },
    Snippet {
        title: "SSH Port Forward",
        lang:  "shell",
        tags:  "ssh tunnel network",
        code:  &[
            "# Local port forward: localhost:8080 -> remote:80",
            "ssh -L 8080:localhost:80 user@server",
            "",
            "# Keep alive in background",
            "ssh -fNL 8080:localhost:80 user@server",
        ],
    },
    Snippet {
        title: "Git Workflow",
        lang:  "shell",
        tags:  "git version control",
        code:  &[
            "git checkout -b feature/my-feature",
            "git add -p                  # interactive stage",
            "git commit -m 'feat: ...'",
            "git push -u origin HEAD",
            "git log --oneline --graph",
        ],
    },
    Snippet {
        title: "Docker Run",
        lang:  "shell",
        tags:  "docker container",
        code:  &[
            "# Run interactively",
            "docker run -it --rm ubuntu:22.04 bash",
            "",
            "# Run with port + volume",
            "docker run -d -p 8080:80 -v $(pwd):/app nginx",
        ],
    },
    Snippet {
        title: "VYOMA_DRAW Helpers",
        lang:  "rust",
        tags:  "vyomaos display draw",
        code:  &[
            "fn fill(x: u32, y: u32, w: u32, h: u32, rgba: u32) {",
            "    println!(\"VYOMA_DRAW:fill_rect:{x},{y},{w},{h},{rgba:#010x}\");",
            "}",
            "fn text(x: u32, y: u32, rgba: u32, s: &str) {",
            "    println!(\"VYOMA_DRAW:draw_text:{x},{y},{rgba:#010x},m,{s}\");",
            "}",
            "fn flush() {",
            "    println!(\"VYOMA_DRAW:flush\");",
            "    let _ = std::io::stdout().flush();",
            "}",
        ],
    },
];
