#!/bin/sh
# rootfs.sh — IoT Raspberry Pi (ARM64) platform initramfs builder
#
# Creates a minimal initramfs for VyomaOS on ARM64 / Raspberry Pi 4.
# Boots from the iot-edge.toml platform profile which selects the wasm3
# runtime and boots only the edge WASM apps declared there.
#
# Usage:
#   bash platforms/iot-rpi/rootfs.sh
#
# Environment variables (optional):
#   RUST_TARGET    — Rust target triple (default: aarch64-unknown-linux-musl)
#   OUT_DIR        — Output directory   (default: out/iot-rpi)
#   WASMTIME_BIN   — Path to wasmtime for ARM64 (default: auto-detected)
#
# Output:
#   $OUT_DIR/initramfs.cpio.gz
set -e

PLATFORM="iot-rpi"
RUST_TARGET="${RUST_TARGET:-aarch64-unknown-linux-musl}"
WASM_TARGET="wasm32-wasip2"
OUT_DIR="${OUT_DIR:-out/iot-rpi}"
PROFILE_SRC="supervisor/src/profile/profiles/iot-edge.toml"
BOOT_TOML_DEST="etc/vyoma/boot.toml"
PROFILE_DEST="etc/vyoma/platform.toml"

# Change to repo root
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

echo "[rootfs:$PLATFORM] Starting rootfs build..."

# ── Create staging directory ──────────────────────────────────────────────────

STAGE="$OUT_DIR/stage"
rm -rf "$STAGE"
mkdir -p \
  "$STAGE/bin" \
  "$STAGE/dev" \
  "$STAGE/etc/vyoma" \
  "$STAGE/etc/vyoma/apps" \
  "$STAGE/proc" \
  "$STAGE/sys" \
  "$STAGE/tmp" \
  "$STAGE/data" \
  "$STAGE/data/ota/a" \
  "$STAGE/data/ota/b" \
  "$STAGE/data/logs"

# ── Copy supervisor binary ────────────────────────────────────────────────────

SUPERVISOR_BIN="supervisor/target/$RUST_TARGET/release/supervisor"
if [ ! -f "$SUPERVISOR_BIN" ]; then
  echo "[rootfs:$PLATFORM] ERROR: supervisor binary not found at $SUPERVISOR_BIN"
  echo "[rootfs:$PLATFORM] Run: cargo build --target $RUST_TARGET --release"
  exit 1
fi
cp "$SUPERVISOR_BIN" "$STAGE/bin/supervisor"
chmod +x "$STAGE/bin/supervisor"
echo "[rootfs:$PLATFORM] supervisor: OK"

# ── Copy wasm3 runtime (or wasmtime as fallback) ──────────────────────────────

# wasm3 is the preferred MCU/IoT runtime (lightweight).
# If a pre-built wasm3 binary for ARM64 is present, use it.
# Otherwise fall back to wasmtime (heavier but compatible).
RUNTIME_BIN=""
if [ -f "out/wasm3-aarch64" ]; then
  RUNTIME_BIN="out/wasm3-aarch64"
  RUNTIME_NAME="wasm3"
elif [ -f "out/wasmtime-aarch64" ]; then
  RUNTIME_BIN="out/wasmtime-aarch64"
  RUNTIME_NAME="wasmtime"
else
  echo "[rootfs:$PLATFORM] WARN: no wasm3 or wasmtime binary found for ARM64"
  echo "[rootfs:$PLATFORM] Continuing without runtime — supervisor mock mode"
  RUNTIME_NAME="mock"
fi

if [ -n "$RUNTIME_BIN" ]; then
  cp "$RUNTIME_BIN" "$STAGE/bin/$RUNTIME_NAME"
  chmod +x "$STAGE/bin/$RUNTIME_NAME"
  # Symlink to /bin/wasmtime for supervisor compatibility
  ln -sf "/bin/$RUNTIME_NAME" "$STAGE/bin/wasmtime"
  echo "[rootfs:$PLATFORM] runtime: $RUNTIME_NAME OK"
fi

# ── Copy BusyBox (minimal userspace) ─────────────────────────────────────────

if [ -f "out/busybox-aarch64" ]; then
  cp "out/busybox-aarch64" "$STAGE/bin/busybox"
  chmod +x "$STAGE/bin/busybox"
  for cmd in sh ls cat grep find mkdir rm cp mv echo true false; do
    ln -sf /bin/busybox "$STAGE/bin/$cmd" 2>/dev/null || true
  done
  echo "[rootfs:$PLATFORM] busybox: OK"
else
  echo "[rootfs:$PLATFORM] WARN: no busybox binary for ARM64 — skipping"
fi

# ── Copy WASM apps ────────────────────────────────────────────────────────────

WASM_COPIED=0
for app_dir in apps/*/; do
  app_name="$(basename "$app_dir")"
  wasm_bin="$app_dir/target/$WASM_TARGET/release/$app_name.wasm"
  if [ -f "$wasm_bin" ]; then
    cp "$wasm_bin" "$STAGE/etc/vyoma/apps/$app_name.wasm"
    WASM_COPIED=$((WASM_COPIED + 1))
  fi
done
echo "[rootfs:$PLATFORM] WASM apps copied: $WASM_COPIED"

# ── Copy app manifests (vyoma.toml → <app>.toml) ─────────────────────────────

for app_dir in apps/*/; do
  app_name="$(basename "$app_dir")"
  manifest="$app_dir/vyoma.toml"
  if [ -f "$manifest" ]; then
    cp "$manifest" "$STAGE/etc/vyoma/apps/$app_name.toml"
  fi
done
echo "[rootfs:$PLATFORM] App manifests copied."

# ── Copy platform profile ────────────────────────────────────────────────────

if [ -f "$PROFILE_SRC" ]; then
  cp "$PROFILE_SRC" "$STAGE/$PROFILE_DEST"
  echo "[rootfs:$PLATFORM] Platform profile: iot-edge.toml"
else
  echo "[rootfs:$PLATFORM] WARN: profile not found at $PROFILE_SRC"
fi

# ── Generate boot.toml from iot-edge.toml boot.apps list ─────────────────────

# The iot-edge.toml profile declares which apps to boot.
# We generate a minimal boot.toml matching those apps.
cat > "$STAGE/$BOOT_TOML_DEST" << 'EOF'
# boot.toml — IoT RPi (ARM64) platform
# Generated by platforms/iot-rpi/rootfs.sh
# Boots apps declared in iot-edge.toml [boot] section.

[[apps]]
manifest = "/etc/vyoma/apps/hello-world.toml"
restart  = "never"

[[apps]]
manifest = "/etc/vyoma/apps/clock.toml"
restart  = "always"
EOF
echo "[rootfs:$PLATFORM] boot.toml generated."

# ── Init script ───────────────────────────────────────────────────────────────

cat > "$STAGE/init" << 'INIT_EOF'
#!/bin/sh
# VyomaOS init — IoT RPi (ARM64)
mount -t proc  proc  /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null || mknod /dev/null c 1 3
# Mount 9P persistent data volume (if available)
mount -t 9p -o trans=virtio,version=9p2000.L data /data 2>/dev/null || true
exec /bin/supervisor
INIT_EOF
chmod +x "$STAGE/init"
echo "[rootfs:$PLATFORM] init script written."

# ── Create device nodes ───────────────────────────────────────────────────────

mkdir -p "$STAGE/dev"
mknod "$STAGE/dev/console" c 5 1 2>/dev/null || true
mknod "$STAGE/dev/null"    c 1 3 2>/dev/null || true
mknod "$STAGE/dev/zero"    c 1 5 2>/dev/null || true
mknod "$STAGE/dev/urandom" c 1 9 2>/dev/null || true

# ── Pack initramfs ────────────────────────────────────────────────────────────

mkdir -p "$OUT_DIR"
(cd "$STAGE" && find . | cpio -H newc -o 2>/dev/null) | gzip -9 > "$OUT_DIR/initramfs.cpio.gz"
echo "[rootfs:$PLATFORM] initramfs written to $OUT_DIR/initramfs.cpio.gz"

# ── Print summary ─────────────────────────────────────────────────────────────

INITRAMFS_SIZE=$(du -h "$OUT_DIR/initramfs.cpio.gz" | cut -f1)
echo "[rootfs:$PLATFORM] Done. initramfs size: $INITRAMFS_SIZE"
echo "[rootfs:$PLATFORM] Boot with: make PLATFORM=iot-rpi run-gui"
