[app]
name    = "network-config"
version = "0.1.0"
wasm    = "network-config.wasm"

[capabilities]
stdio      = true
display    = true
shell      = true
network    = true
filesystem = true

[window]
x = 300
y = 100
w = 900
h = 700
