[app]
name    = "settings"
version = "0.1.0"
wasm    = "settings.wasm"
icon    = "icon.png"

[capabilities]
stdio      = true
display    = true
shell      = true
filesystem = true
mouse      = true

[window]
x = 720
y = 580
w = 700
h = 280
